import { redirect } from "next/navigation";
import { getSession } from "@/lib/session";
import { buildReport } from "@/lib/reports";
import { istDayRangeFromISO, istISODate, istDate } from "@/lib/date";
import AutoPrint from "./AutoPrint";

export const dynamic = "force-dynamic";

export default async function ReportPrintPage({
  searchParams,
}: {
  searchParams: Promise<{ from?: string; to?: string }>;
}) {
  const session = await getSession();
  if (!session) redirect("/login");

  const { from, to } = await searchParams;
  const todayIso = istISODate();
  const fromIso = from || todayIso;
  const toIso = to || fromIso;
  const { start } = istDayRangeFromISO(fromIso);
  const { end } = istDayRangeFromISO(toIso);
  const data = await buildReport(start, end);
  const c = data.counts;
  const clinicName = process.env.CLINIC_NAME || "Cardineo Heart Clinic";

  return (
    <main className="mx-auto max-w-4xl bg-white p-8 text-slate-900">
      <AutoPrint />
      <div className="mb-4 flex items-end justify-between border-b border-slate-300 pb-3">
        <div>
          <h1 className="text-2xl font-bold">{clinicName}</h1>
          <p className="text-slate-600">Daily Summary</p>
        </div>
        <div className="text-right text-sm text-slate-600">
          <div>{fromIso === toIso ? istDate(start) : `${istDate(start)} → ${istDate(new Date(end.getTime() - 1))}`}</div>
          <div className="no-print mt-1 text-xs text-slate-400">Print dialog opens automatically — save as PDF.</div>
        </div>
      </div>

      {/* KPI blocks */}
      <div className="mb-6 grid grid-cols-4 gap-3">
        {[
          ["Forms filled", c.filled],
          ["Consulted", c.consulted],
          ["Walk-ins", c.walkIns],
          ["With appt.", c.appointments],
          ["No-shows", c.noShows],
          ["Urgent", c.urgent],
          ["Follow-ups", c.followUpsScheduled],
          ["Avg form→consult", c.avgFormToConsultMin != null ? `${c.avgFormToConsultMin}m` : "—"],
        ].map(([label, value]) => (
          <div key={label as string} className="rounded-lg border border-slate-200 p-3">
            <div className="text-xl font-bold">{value}</div>
            <div className="text-xs text-slate-500">{label}</div>
          </div>
        ))}
      </div>

      <div className="mb-4 text-sm text-slate-700">
        Visit types — First: {c.first}, Repeat: {c.repeat}, Follow-up: {c.followUp}
      </div>

      {/* Table */}
      <table className="w-full border-collapse text-xs">
        <thead>
          <tr className="border-b-2 border-slate-300 text-left">
            <th className="py-1.5 pr-2">Token</th>
            <th className="py-1.5 pr-2">Name</th>
            <th className="py-1.5 pr-2">Age/Sex</th>
            <th className="py-1.5 pr-2">Visit</th>
            <th className="py-1.5 pr-2">Complaint</th>
            <th className="py-1.5 pr-2">Diagnosis</th>
            <th className="py-1.5 pr-2">Follow-up</th>
            <th className="py-1.5 pr-2">Status</th>
          </tr>
        </thead>
        <tbody>
          {data.rows.map((r, i) => (
            <tr key={i} className="border-b border-slate-100 align-top">
              <td className="py-1 pr-2">#{r.token}</td>
              <td className="py-1 pr-2">{r.name}</td>
              <td className="py-1 pr-2">{r.age} {r.gender}</td>
              <td className="py-1 pr-2">{r.visitType}</td>
              <td className="py-1 pr-2">{r.complaint}</td>
              <td className="py-1 pr-2">{r.diagnosis || "—"}</td>
              <td className="py-1 pr-2">{r.followUpDate || "—"}</td>
              <td className="py-1 pr-2">{r.status}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p className="mt-6 text-xs text-slate-400">
        Generated by CardioIntake · {istDate(new Date())} · Times in IST
      </p>
    </main>
  );
}
